language: php

php: ["5.3", "5.4", "5.5", "5.6", "hhvm"]

matrix:
    allow_failures: [{"php": "5.6"}, {"php": "hhvm"}]
    fast_finish: true

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "ZWgcdKk31pY8CRq3LUkYT11mwrHfTTnt1F1e3EUDWTTdkUD/We1nICdsDdL9MD8u6vMfkWsywJy9+F8XW9lvcJ535gyPRofAkoP0aK7p+d8XdTDeS5ZWhI1l0En69Cf259kdTAdJQfwwA2HsFjE1e+xnnZkMzRNVOnW+jUxck+E="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
