var tree = [["Eloquent",,"",
                [["Schemer",,"",
                [["Constraint","Eloquent\/Schemer\/Constraint.html","",
                [["ArrayValue","Eloquent\/Schemer\/Constraint\/ArrayValue.html","",
                [["AdditionalItemConstraint","Eloquent\/Schemer\/Constraint\/ArrayValue\/AdditionalItemConstraint.html","",
                [        ]],["ItemsConstraint","Eloquent\/Schemer\/Constraint\/ArrayValue\/ItemsConstraint.html","",
                [        ]],["MaximumItemsConstraint","Eloquent\/Schemer\/Constraint\/ArrayValue\/MaximumItemsConstraint.html","",
                [        ]],["MinimumItemsConstraint","Eloquent\/Schemer\/Constraint\/ArrayValue\/MinimumItemsConstraint.html","",
                [        ]],["UniqueItemsConstraint","Eloquent\/Schemer\/Constraint\/ArrayValue\/UniqueItemsConstraint.html","",
                [        ]]        ]],["DateTimeValue","Eloquent\/Schemer\/Constraint\/DateTimeValue.html","",
                [["MaximumDateTimeConstraint","Eloquent\/Schemer\/Constraint\/DateTimeValue\/MaximumDateTimeConstraint.html","",
                [        ]],["MinimumDateTimeConstraint","Eloquent\/Schemer\/Constraint\/DateTimeValue\/MinimumDateTimeConstraint.html","",
                [        ]]        ]],["Factory","Eloquent\/Schemer\/Constraint\/Factory.html","",
                [["FormatConstraintFactory","Eloquent\/Schemer\/Constraint\/Factory\/FormatConstraintFactory.html","",
                [        ]],["FormatConstraintFactoryInterface","Eloquent\/Schemer\/Constraint\/Factory\/FormatConstraintFactoryInterface.html","",
                [        ]],["MetaSchemaFactory","Eloquent\/Schemer\/Constraint\/Factory\/MetaSchemaFactory.html","",
                [        ]],["SchemaFactory","Eloquent\/Schemer\/Constraint\/Factory\/SchemaFactory.html","",
                [        ]],["SchemaFactoryInterface","Eloquent\/Schemer\/Constraint\/Factory\/SchemaFactoryInterface.html","",
                [        ]]        ]],["Generic","Eloquent\/Schemer\/Constraint\/Generic.html","",
                [["AbstractSchemaSetConstraint","Eloquent\/Schemer\/Constraint\/Generic\/AbstractSchemaSetConstraint.html","",
                [        ]],["AllOfConstraint","Eloquent\/Schemer\/Constraint\/Generic\/AllOfConstraint.html"," < AbstractSchemaSetConstraint",
                [        ]],["AnyOfConstraint","Eloquent\/Schemer\/Constraint\/Generic\/AnyOfConstraint.html"," < AbstractSchemaSetConstraint",
                [        ]],["EnumConstraint","Eloquent\/Schemer\/Constraint\/Generic\/EnumConstraint.html","",
                [        ]],["NotConstraint","Eloquent\/Schemer\/Constraint\/Generic\/NotConstraint.html","",
                [        ]],["OneOfConstraint","Eloquent\/Schemer\/Constraint\/Generic\/OneOfConstraint.html"," < AbstractSchemaSetConstraint",
                [        ]],["SchemaSetConstraintInterface","Eloquent\/Schemer\/Constraint\/Generic\/SchemaSetConstraintInterface.html","",
                [        ]],["TypeConstraint","Eloquent\/Schemer\/Constraint\/Generic\/TypeConstraint.html","",
                [        ]]        ]],["NumberValue","Eloquent\/Schemer\/Constraint\/NumberValue.html","",
                [["MaximumConstraint","Eloquent\/Schemer\/Constraint\/NumberValue\/MaximumConstraint.html","",
                [        ]],["MinimumConstraint","Eloquent\/Schemer\/Constraint\/NumberValue\/MinimumConstraint.html","",
                [        ]],["MultipleOfConstraint","Eloquent\/Schemer\/Constraint\/NumberValue\/MultipleOfConstraint.html","",
                [        ]]        ]],["ObjectValue","Eloquent\/Schemer\/Constraint\/ObjectValue.html","",
                [["AdditionalPropertyConstraint","Eloquent\/Schemer\/Constraint\/ObjectValue\/AdditionalPropertyConstraint.html","",
                [        ]],["DependencyConstraint","Eloquent\/Schemer\/Constraint\/ObjectValue\/DependencyConstraint.html","",
                [        ]],["MaximumPropertiesConstraint","Eloquent\/Schemer\/Constraint\/ObjectValue\/MaximumPropertiesConstraint.html","",
                [        ]],["MinimumPropertiesConstraint","Eloquent\/Schemer\/Constraint\/ObjectValue\/MinimumPropertiesConstraint.html","",
                [        ]],["PropertiesConstraint","Eloquent\/Schemer\/Constraint\/ObjectValue\/PropertiesConstraint.html","",
                [        ]],["RequiredConstraint","Eloquent\/Schemer\/Constraint\/ObjectValue\/RequiredConstraint.html","",
                [        ]]        ]],["Reader","Eloquent\/Schemer\/Constraint\/Reader.html","",
                [["SchemaReader","Eloquent\/Schemer\/Constraint\/Reader\/SchemaReader.html","",
                [        ]],["SchemaReaderInterface","Eloquent\/Schemer\/Constraint\/Reader\/SchemaReaderInterface.html","",
                [        ]]        ]],["Renderer","Eloquent\/Schemer\/Constraint\/Renderer.html","",
                [["ConstraintFailureRenderer","Eloquent\/Schemer\/Constraint\/Renderer\/ConstraintFailureRenderer.html","",
                [        ]]        ]],["StringValue","Eloquent\/Schemer\/Constraint\/StringValue.html","",
                [["DateTimeFormatConstraint","Eloquent\/Schemer\/Constraint\/StringValue\/DateTimeFormatConstraint.html","",
                [        ]],["EmailFormatConstraint","Eloquent\/Schemer\/Constraint\/StringValue\/EmailFormatConstraint.html","",
                [        ]],["HostnameFormatConstraint","Eloquent\/Schemer\/Constraint\/StringValue\/HostnameFormatConstraint.html","",
                [        ]],["Ipv4AddressFormatConstraint","Eloquent\/Schemer\/Constraint\/StringValue\/Ipv4AddressFormatConstraint.html","",
                [        ]],["Ipv6AddressFormatConstraint","Eloquent\/Schemer\/Constraint\/StringValue\/Ipv6AddressFormatConstraint.html","",
                [        ]],["MaximumLengthConstraint","Eloquent\/Schemer\/Constraint\/StringValue\/MaximumLengthConstraint.html","",
                [        ]],["MinimumLengthConstraint","Eloquent\/Schemer\/Constraint\/StringValue\/MinimumLengthConstraint.html","",
                [        ]],["PatternConstraint","Eloquent\/Schemer\/Constraint\/StringValue\/PatternConstraint.html","",
                [        ]],["UriFormatConstraint","Eloquent\/Schemer\/Constraint\/StringValue\/UriFormatConstraint.html","",
                [        ]]        ]],["Transform","Eloquent\/Schemer\/Constraint\/Transform.html","",
                [["AbstractConstraintTransform","Eloquent\/Schemer\/Constraint\/Transform\/AbstractConstraintTransform.html","",
                [        ]],["ConstraintTransformInterface","Eloquent\/Schemer\/Constraint\/Transform\/ConstraintTransformInterface.html","",
                [        ]]        ]],["Visitor","Eloquent\/Schemer\/Constraint\/Visitor.html","",
                [["ConstraintVisitorInterface","Eloquent\/Schemer\/Constraint\/Visitor\/ConstraintVisitorInterface.html","",
                [        ]]        ]],["ConstraintInterface","Eloquent\/Schemer\/Constraint\/ConstraintInterface.html","",
                [        ]],["FormatConstraintInterface","Eloquent\/Schemer\/Constraint\/FormatConstraintInterface.html","",
                [        ]],["Schema","Eloquent\/Schemer\/Constraint\/Schema.html","",
                [        ]],["SchemaInterface","Eloquent\/Schemer\/Constraint\/SchemaInterface.html","",
                [        ]]        ]],["Loader","Eloquent\/Schemer\/Loader.html","",
                [["Data","Eloquent\/Schemer\/Loader\/Data.html","",
                [["DataLoader","Eloquent\/Schemer\/Loader\/Data\/DataLoader.html","",
                [        ]]        ]],["Exception","Eloquent\/Schemer\/Loader\/Exception.html","",
                [["LoadException","Eloquent\/Schemer\/Loader\/Exception\/LoadException.html"," < RuntimeException",
                [        ]],["LoadExceptionInterface","Eloquent\/Schemer\/Loader\/Exception\/LoadExceptionInterface.html","",
                [        ]],["UndefinedLoaderException","Eloquent\/Schemer\/Loader\/Exception\/UndefinedLoaderException.html"," < LogicException",
                [        ]]        ]],["FileSystem","Eloquent\/Schemer\/Loader\/FileSystem.html","",
                [["ExtensionTypeMap","Eloquent\/Schemer\/Loader\/FileSystem\/ExtensionTypeMap.html","",
                [        ]],["FileSystemLoader","Eloquent\/Schemer\/Loader\/FileSystem\/FileSystemLoader.html","",
                [        ]]        ]],["Http","Eloquent\/Schemer\/Loader\/Http.html","",
                [["HttpLoader","Eloquent\/Schemer\/Loader\/Http\/HttpLoader.html","",
                [        ]]        ]],["Content","Eloquent\/Schemer\/Loader\/Content.html","",
                [        ]],["ContentType","Eloquent\/Schemer\/Loader\/ContentType.html"," < Multiton",
                [        ]],["Loader","Eloquent\/Schemer\/Loader\/Loader.html","",
                [        ]],["LoaderInterface","Eloquent\/Schemer\/Loader\/LoaderInterface.html","",
                [        ]]        ]],["Pointer","Eloquent\/Schemer\/Pointer.html","",
                [["Exception","Eloquent\/Schemer\/Pointer\/Exception.html","",
                [["InvalidPointerException","Eloquent\/Schemer\/Pointer\/Exception\/InvalidPointerException.html"," < Exception",
                [        ]]        ]],["Resolver","Eloquent\/Schemer\/Pointer\/Resolver.html","",
                [["Exception","Eloquent\/Schemer\/Pointer\/Resolver\/Exception.html","",
                [["UndefinedValueException","Eloquent\/Schemer\/Pointer\/Resolver\/Exception\/UndefinedValueException.html"," < Exception",
                [        ]]        ]],["PointerResolver","Eloquent\/Schemer\/Pointer\/Resolver\/PointerResolver.html","",
                [        ]],["PointerResolverInterface","Eloquent\/Schemer\/Pointer\/Resolver\/PointerResolverInterface.html","",
                [        ]]        ]],["Pointer","Eloquent\/Schemer\/Pointer\/Pointer.html","",
                [        ]],["PointerFactory","Eloquent\/Schemer\/Pointer\/PointerFactory.html","",
                [        ]],["PointerFactoryInterface","Eloquent\/Schemer\/Pointer\/PointerFactoryInterface.html","",
                [        ]],["PointerInterface","Eloquent\/Schemer\/Pointer\/PointerInterface.html","",
                [        ]]        ]],["Reader","Eloquent\/Schemer\/Reader.html","",
                [["AbstractReader","Eloquent\/Schemer\/Reader\/AbstractReader.html","",
                [        ]],["AbstractResolvingReader","Eloquent\/Schemer\/Reader\/AbstractResolvingReader.html"," < AbstractReader",
                [        ]],["FixedScopeResolvingReader","Eloquent\/Schemer\/Reader\/FixedScopeResolvingReader.html"," < AbstractResolvingReader",
                [        ]],["Reader","Eloquent\/Schemer\/Reader\/Reader.html"," < AbstractReader",
                [        ]],["ReaderInterface","Eloquent\/Schemer\/Reader\/ReaderInterface.html","",
                [        ]],["SwitchingScopeResolvingReader","Eloquent\/Schemer\/Reader\/SwitchingScopeResolvingReader.html"," < AbstractResolvingReader",
                [        ]]        ]],["Reference","Eloquent\/Schemer\/Reference.html","",
                [["Exception","Eloquent\/Schemer\/Reference\/Exception.html","",
                [["UndefinedReferenceException","Eloquent\/Schemer\/Reference\/Exception\/UndefinedReferenceException.html"," < Exception",
                [        ]]        ]],["FixedResolutionScopeMapFactory","Eloquent\/Schemer\/Reference\/FixedResolutionScopeMapFactory.html"," < AbstractValueVisitor",
                [        ]],["FixedScopeReferenceResolverFactory","Eloquent\/Schemer\/Reference\/FixedScopeReferenceResolverFactory.html","",
                [        ]],["ReferenceResolver","Eloquent\/Schemer\/Reference\/ReferenceResolver.html"," < AbstractValueTransform",
                [        ]],["ReferenceResolverFactoryInterface","Eloquent\/Schemer\/Reference\/ReferenceResolverFactoryInterface.html","",
                [        ]],["ResolutionScopeMap","Eloquent\/Schemer\/Reference\/ResolutionScopeMap.html","",
                [        ]],["ResolutionScopeMapFactoryInterface","Eloquent\/Schemer\/Reference\/ResolutionScopeMapFactoryInterface.html","",
                [        ]],["SwitchingResolutionScopeMapFactory","Eloquent\/Schemer\/Reference\/SwitchingResolutionScopeMapFactory.html"," < AbstractValueVisitor",
                [        ]],["SwitchingScopeReferenceResolverFactory","Eloquent\/Schemer\/Reference\/SwitchingScopeReferenceResolverFactory.html","",
                [        ]]        ]],["Serialization","Eloquent\/Schemer\/Serialization.html","",
                [["Exception","Eloquent\/Schemer\/Serialization\/Exception.html","",
                [["ThawExceptionInterface","Eloquent\/Schemer\/Serialization\/Exception\/ThawExceptionInterface.html","",
                [        ]],["UndefinedProtocolException","Eloquent\/Schemer\/Serialization\/Exception\/UndefinedProtocolException.html"," < LogicException",
                [        ]]        ]],["Json","Eloquent\/Schemer\/Serialization\/Json.html","",
                [["Exception","Eloquent\/Schemer\/Serialization\/Json\/Exception.html","",
                [["JsonThawException","Eloquent\/Schemer\/Serialization\/Json\/Exception\/JsonThawException.html"," < Exception",
                [        ]]        ]],["JsonProtocol","Eloquent\/Schemer\/Serialization\/Json\/JsonProtocol.html","",
                [        ]]        ]],["Toml","Eloquent\/Schemer\/Serialization\/Toml.html","",
                [["Exception","Eloquent\/Schemer\/Serialization\/Toml\/Exception.html","",
                [["TomlThawException","Eloquent\/Schemer\/Serialization\/Toml\/Exception\/TomlThawException.html"," < Exception",
                [        ]]        ]],["TomlProtocol","Eloquent\/Schemer\/Serialization\/Toml\/TomlProtocol.html","",
                [        ]]        ]],["Yaml","Eloquent\/Schemer\/Serialization\/Yaml.html","",
                [["Exception","Eloquent\/Schemer\/Serialization\/Yaml\/Exception.html","",
                [["YamlThawException","Eloquent\/Schemer\/Serialization\/Yaml\/Exception\/YamlThawException.html"," < Exception",
                [        ]]        ]],["YamlProtocol","Eloquent\/Schemer\/Serialization\/Yaml\/YamlProtocol.html","",
                [        ]]        ]],["ProtocolMap","Eloquent\/Schemer\/Serialization\/ProtocolMap.html","",
                [        ]],["SerializationProtocolInterface","Eloquent\/Schemer\/Serialization\/SerializationProtocolInterface.html","",
                [        ]]        ]],["Uri","Eloquent\/Schemer\/Uri.html","",
                [["Resolver","Eloquent\/Schemer\/Uri\/Resolver.html","",
                [["BoundUriResolver","Eloquent\/Schemer\/Uri\/Resolver\/BoundUriResolver.html","",
                [        ]],["BoundUriResolverInterface","Eloquent\/Schemer\/Uri\/Resolver\/BoundUriResolverInterface.html","",
                [        ]],["UriResolver","Eloquent\/Schemer\/Uri\/Resolver\/UriResolver.html","",
                [        ]],["UriResolverInterface","Eloquent\/Schemer\/Uri\/Resolver\/UriResolverInterface.html","",
                [        ]]        ]],["DataUri","Eloquent\/Schemer\/Uri\/DataUri.html"," < Uri",
                [        ]],["HttpUri","Eloquent\/Schemer\/Uri\/HttpUri.html"," < Uri",
                [        ]],["Uri","Eloquent\/Schemer\/Uri\/Uri.html"," < Uri",
                [        ]],["UriFactory","Eloquent\/Schemer\/Uri\/UriFactory.html","",
                [        ]],["UriFactoryInterface","Eloquent\/Schemer\/Uri\/UriFactoryInterface.html","",
                [        ]]        ]],["Validation","Eloquent\/Schemer\/Validation.html","",
                [["Result","Eloquent\/Schemer\/Validation\/Result.html","",
                [["AbstractMatch","Eloquent\/Schemer\/Validation\/Result\/AbstractMatch.html","",
                [        ]],["DefaultValueMatch","Eloquent\/Schemer\/Validation\/Result\/DefaultValueMatch.html"," < AbstractMatch",
                [        ]],["IssueRenderer","Eloquent\/Schemer\/Validation\/Result\/IssueRenderer.html","",
                [        ]],["IssueRendererInterface","Eloquent\/Schemer\/Validation\/Result\/IssueRendererInterface.html","",
                [        ]],["MatchInterface","Eloquent\/Schemer\/Validation\/Result\/MatchInterface.html","",
                [        ]],["ValidationIssue","Eloquent\/Schemer\/Validation\/Result\/ValidationIssue.html","",
                [        ]],["ValidationMatch","Eloquent\/Schemer\/Validation\/Result\/ValidationMatch.html"," < AbstractMatch",
                [        ]],["ValidationResult","Eloquent\/Schemer\/Validation\/Result\/ValidationResult.html","",
                [        ]]        ]],["BoundConstraintValidator","Eloquent\/Schemer\/Validation\/BoundConstraintValidator.html","",
                [        ]],["BoundConstraintValidatorInterface","Eloquent\/Schemer\/Validation\/BoundConstraintValidatorInterface.html","",
                [        ]],["ConstraintValidator","Eloquent\/Schemer\/Validation\/ConstraintValidator.html","",
                [        ]],["ConstraintValidatorInterface","Eloquent\/Schemer\/Validation\/ConstraintValidatorInterface.html","",
                [        ]],["DefaultValueTransform","Eloquent\/Schemer\/Validation\/DefaultValueTransform.html"," < AbstractValueTransform",
                [        ]],["DefaultValueTransformFactory","Eloquent\/Schemer\/Validation\/DefaultValueTransformFactory.html","",
                [        ]],["DefaultingConstraintValidator","Eloquent\/Schemer\/Validation\/DefaultingConstraintValidator.html","",
                [        ]],["DefaultingConstraintValidatorInterface","Eloquent\/Schemer\/Validation\/DefaultingConstraintValidatorInterface.html","",
                [        ]]        ]],["Value","Eloquent\/Schemer\/Value.html","",
                [["Exception","Eloquent\/Schemer\/Value\/Exception.html","",
                [["UndefinedPropertyException","Eloquent\/Schemer\/Value\/Exception\/UndefinedPropertyException.html"," < Exception",
                [        ]]        ]],["Factory","Eloquent\/Schemer\/Value\/Factory.html","",
                [["ValueFactory","Eloquent\/Schemer\/Value\/Factory\/ValueFactory.html","",
                [        ]],["ValueFactoryInterface","Eloquent\/Schemer\/Value\/Factory\/ValueFactoryInterface.html","",
                [        ]]        ]],["Transform","Eloquent\/Schemer\/Value\/Transform.html","",
                [["AbstractValueTransform","Eloquent\/Schemer\/Value\/Transform\/AbstractValueTransform.html"," < AbstractValueVisitor",
                [        ]],["PlaceholderUnwrapTransform","Eloquent\/Schemer\/Value\/Transform\/PlaceholderUnwrapTransform.html"," < AbstractValueTransform",
                [        ]],["ValueTransformInterface","Eloquent\/Schemer\/Value\/Transform\/ValueTransformInterface.html","",
                [        ]]        ]],["Visitor","Eloquent\/Schemer\/Value\/Visitor.html","",
                [["AbstractValueVisitor","Eloquent\/Schemer\/Value\/Visitor\/AbstractValueVisitor.html","",
                [        ]],["ValueVisitorInterface","Eloquent\/Schemer\/Value\/Visitor\/ValueVisitorInterface.html","",
                [        ]]        ]],["AbstractConcreteValue","Eloquent\/Schemer\/Value\/AbstractConcreteValue.html","",
                [        ]],["ArrayValue","Eloquent\/Schemer\/Value\/ArrayValue.html"," < AbstractConcreteValue",
                [        ]],["BooleanValue","Eloquent\/Schemer\/Value\/BooleanValue.html"," < AbstractConcreteValue",
                [        ]],["ConcreteValueInterface","Eloquent\/Schemer\/Value\/ConcreteValueInterface.html","",
                [        ]],["DateTimeValue","Eloquent\/Schemer\/Value\/DateTimeValue.html"," < AbstractConcreteValue",
                [        ]],["FloatingPointValue","Eloquent\/Schemer\/Value\/FloatingPointValue.html"," < AbstractConcreteValue",
                [        ]],["IntegerValue","Eloquent\/Schemer\/Value\/IntegerValue.html"," < AbstractConcreteValue",
                [        ]],["NullValue","Eloquent\/Schemer\/Value\/NullValue.html"," < AbstractConcreteValue",
                [        ]],["NumberValueInterface","Eloquent\/Schemer\/Value\/NumberValueInterface.html","",
                [        ]],["ObjectValue","Eloquent\/Schemer\/Value\/ObjectValue.html"," < AbstractConcreteValue",
                [        ]],["PlaceholderValue","Eloquent\/Schemer\/Value\/PlaceholderValue.html","",
                [        ]],["ReferenceValue","Eloquent\/Schemer\/Value\/ReferenceValue.html","",
                [        ]],["StringValue","Eloquent\/Schemer\/Value\/StringValue.html"," < AbstractConcreteValue",
                [        ]],["ValueContainerInterface","Eloquent\/Schemer\/Value\/ValueContainerInterface.html","",
                [        ]],["ValueInterface","Eloquent\/Schemer\/Value\/ValueInterface.html","",
                [        ]],["ValueType","Eloquent\/Schemer\/Value\/ValueType.html"," < Enumeration",
                [        ]]        ]]        ]]        ]]        ]

